# CUDA_VISIBLE_DEVICES=0 python evaluate_model.py -m stain_modality=HE,KI67,Early_Fusion_HE_KI67

#; CUDA_VISIBLE_DEVICES=0 python evaluate_model.py -m stain_modality=HE,KI67,Early_Fusion_HE_KI67 feature_type=resnet50 embed_dim=1024 

# CUDA_VISIBLE_DEVICES=0 python evaluate_model.py -m stain_modality=Early_Fusion_HE_only,Early_Fusion_KI67_only

hydra:
  searchpath:
    - /local/data1/chrsp39/CBTN_Histology_Multi_Stain/configs

defaults:
- _self_
- stain_modality : HE

# random seed for reproducibility
seed: 1

# -------------------------- CLASSIFICATION SETTINGS -------------------------- #
# classification task
task: 5_class # LGG_vs_HGG, 5_class, 
# number of class
n_classes: 5
# class labels
label_dict :
  LGG: 0
  HGG: 1
  MB: 2
  EP: 3
  GG: 4
  # MEN: 5
  # ATRT: 6
  # DNET: 7
  # DIPG: 8

# -------------------------- DATA SETTINGS -------------------------- #
# path to csv file
csv_path: /local/data3/chrsp39/CBTN_v2/CSVs/Merged_HE_KI67_${task}_dataset.csv
# stratify samples by patient
patient_strat: False
# shuffle the data before training
shuffle: False
# information during the training
print_info: True
# number of folds
k: 50
# start fold 
k_start: -1 # (default: -1, last fold)
# end fold
k_end: -1 # (default: -1, first fold)
# single fold to evaluate
fold: -1 # (default: -1)
# splits directory
splits_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/splits/Merged_HE_KI67_${task}_0.7_0.1_0.2_100

# -------------------------- FEATURE SETTINGS -------------------------- #
# directory to features
data_root_dir: # defined in a separate yaml file
# type of feature
feature_type: uni # options: resnet50, hipt, uni, uni2-h, conch_v1_5, conch_v1
# dimensionality of features
embed_dim: 1024 # options: 1536 (uni2-h), 1024 (uni, resnet50), 768 (conch_v1_5), 512 (conch_v1)

# -------------------------- RESULTS SETTINGS -------------------------- #
# results directory
results_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/results/${task}
# experiment code to save eval results
save_exp_code: # defined in a separate yaml file
# experiment code to load trained models
models_exp_code: # defined in a separate yaml file

# -------------------------- TESTING SETTINGS -------------------------- #
# aggregation menthod
model_type: clam_sb #options: clam_sb, clam_mb, mil, abmil
# size of model, does not affect mil, abmil
model_size: small # options small, big
# whether model uses dropout
drop_out: False # needs to be True for abmil, since the checkpoint was trained with dropout enabled. Setting drop_out to 
              # True the index of the attention layer is shifted to match the checkpoint structure. So dropout is not 
              # actual used in the test phase but is set to True to shift the indices.
# use micro_average instead of macro_avearge for multiclass AUC
micro_average: False
split: train # options: train, val, test, all
save_logits: True
ignore: null