description : 'KI67' 

# directory to features
features_dir: /local/data3/chrsp39/CBTN_v2/Merged_KI67/features/${feature_type}/pt_files
# experiment code to load trained models
models_exp_code: ${task}_${stain_modality.description}_${model_size}_${model_type}_${feature_type}_s1
# directory for saving the subject level attention
save_dir: /local/data3/chrsp39/CBTN_v2/SUBJECT_LEVEL_ATTENTION_KI67/features/${feature_type}/${split}/pt_files

