# python stack_features.py

# input paths for modality pt_files directories
first_modality_pt_files: "/local/data3/chrsp39/CBTN_v2/Merged_HE/features/conch_v1/pt_files"
second_modality_pt_files: "/local/data3/chrsp39/CBTN_v2/Merged_KI67/features/conch_v1/pt_files"

# stacking options - set to True to enable, False to disable
stack_single_modality: True
stack_double_modality: True

# output directories for stacked features
saved_stack_single_modality: "/local/data3/chrsp39/CBTN_v2/Merged_KI67/features/conch_v1/pt_files"
saved_stack_double_modality: "/local/data3/chrsp39/CBTN_v2/Merged_HE_KI67/features/conch_v1/pt_files"
