# CUDA_VISIBLE_DEVICES=0 python run_age_fusion.py

hydra:
  searchpath:
    - /local/data1/chrsp39/CBTN_Histology_Multi_Stain/configs

defaults:
- _self_

# random seed for reproducibility
seed: 1

# -------------------------- CLASSIFICATION SETTINGS -------------------------- #
# classification task
task: LGG_vs_HGG
# number of classes 
n_classes: 2
# class labels
label_dict:
  LGG: 0
  HGG: 1

# -------------------------- DATA SETTINGS -------------------------- #
# path to csv file
csv_path: /local/data3/chrsp39/CBTN_v2/CSVs/Merged_HE_KI67_${task}_dataset.csv
# path to Excel file with age information
excel_path: /local/data3/chrsp39/CBTN_v2/CSVs/CBTN_clinical_data_from_portal.xlsx
# path to pre-computed subject-level features
feature_path: /local/data3/chrsp39/CBTN_v2/Learned_Subject_Level_Features/${task}/Merged_HE/features/${feature_type}/pt_files
# directory to splits
split_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/splits/Merged_HE_KI67_${task}_0.7_0.1_0.2_100

# number of folds
k: 50
# start fold 
k_start: 0
# end fold  
k_end: 50

# -------------------------- FEATURE SETTINGS -------------------------- #
# type of feature
feature_type: conch_v1
# dimensionality of features
embed_dim: 512
# dimensionality of age encoding
age_dim: 3

# -------------------------- TRAINING SETTINGS -------------------------- #
# maximum number of training epochs
max_epochs: 50
# enable early stopping
early_stopping: True
# learning rate
lr: 0.0001
# learning rate scheduler
lr_scheduler: cosine
# optimizer
opt: adamW
# weight decay
reg: 1e-5
# dropout rate
drop_out: 0.25
# batch size
batch_size: 1
# enable training and validation
enable_training: True
# enable testing
enable_testing: True

# -------------------------- OUTPUT SETTINGS -------------------------- #
# results directory for trained models
results_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/results/${task}
# evaluation results directory for test predictions
eval_results_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/eval_results/${task}
# experiment name for saving model files
model_exp_code: ${task}_HE_age_fusion_small_clam_sb_${feature_type}_s1
# experiment name for saving evaluation results
eval_exp_code: EVAL_${task}_HE_age_fusion_small_clam_sb_${feature_type}