# CUDA_VISIBLE_DEVICES=0 python create_patches_fp.py
# CUDA_VISIBLE_DEVICES=0 python create_patches_fp_tif.py

# -------------------------- DIRECTORY SETTINGS -------------------------- #
# path to folder containing raw wsi image files
source: /local/data3/chrsp39/CBTN_v2/new_KI67/WSI_tif
# directory to save processed data
save_dir: /local/data3/chrsp39/CBTN_v2/new_KI67/${patch_size}x${patch_size}_tif

# --------------------------- PROCESSING SETTINGS -------------------------- #
# perfrom patching
patch: True
# perform segmentation
seg: True
# perform stitching
stitch: True
# saved masked images
save_mask: True
# skip or not processed slides
no_auto_skip: True
# predefined profile of default segmentation and filter parameters (.csv)
preset: False
# name of list of images to process with parameters (.csv)
process_list: False
# use default segmentation and filter parameters
use_default_params: False

# -------------------------- PATCH SETTINGS -------------------------- #
# patch parameters
# step_size
step_size: 224
# patch_size
patch_size: 224
# downsample level at which to patch
patch_level: 0
# use padding when extracting patches
use_padding: False
# contour to use for patching
contour_fn: four_pt

# -------------------------- PATCH FILTERING THRESHOLDS -------------------------- #
# white patch detection - saturation threshold (HSV S channel)
satThresh: 5
# white patch detection - brightness threshold (HSV V channel)
brightnessThresh: 210
# black patch detection - RGB threshold
rgbThresh: 40

# segmentation parameters
seg_level: -1
sthresh: 2
mthresh: 7
close: 60
use_otsu: False
keep_ids: none
exclude_ids: none
ref_patch_size: 512

# filter parameters
a_t: 1
a_h: 1000000000000
max_n_holes: 10000000000000

# vision parameters
vis_level: -1
line_thickness: 70
