# CUDA_VISIBLE_DEVICES=0 python create_patches_fp.py

# -------------------------- DIRECTORY SETTINGS -------------------------- #
# path to folder containing raw wsi image files
source: /local/data3/chrsp39/CBTN_v2/new_KI67/WSI_svs
# directory to save processed data
save_dir: /local/data3/chrsp39/CBTN_v2/new_KI67/${patch_size}x${patch_size}_svs

# --------------------------- PROCESSING SETTINGS -------------------------- #
# perfrom patching
patch: True
# perform segmentation
seg: True
# perform stitching
stitch: True
# saved masked images
save_mask: True
# skip or not processed slides
no_auto_skip: True
# predefined profile of default segmentation and filter parameters (.csv)
preset: False
# name of list of images to process with parameters (.csv)
process_list: False
# use default segmentation and filter parameters
use_default_params: False

# -------------------------- PATCH SETTINGS -------------------------- #
# patch parameters
# step_size
step_size: 224
# patch_size
patch_size: 224
# downsample level at which to patch
patch_level: 0
# use padding when extracting patches
use_padding: True
# contour to use for patching
contour_fn: four_pt

# segmentation parameters
seg_level: -1
sthresh: 8
mthresh: 7
close: 4
use_otsu: True
keep_ids: none
exclude_ids: none
ref_patch_size: 512

# filter parameters
a_t: 1
a_h: 100
max_n_holes: 10000000

# vision parameters
vis_level: -1
line_thickness: 70
