# CUDA_VISIBLE_DEVICES=0 python extract_features_fp.py

# random seed for reproducibility
seed: 1
# slide file extension
slide_ext: .svs
# feature extractor selection
model_name: virchow # options: resnet50, uni_vit, conch_vit, hipt_vit, prov-gigapath, virchow, virchow2
# batch size for data loading
batch_size: 128
# size of h5 files in GB (only when using virchow and virchow2)
dataset_size_gb: 50 # adjust the size of h5 files to be loaded in memory directly or in chunks if there is memory allocation issues  
# number of worker threads for data loading
num_workers: 12
# skip or not processed slides
auto_skip: True
# image patch size 
target_patch_size: 224 # resnet50, uni, conch & hipt use 256x256 patch size - prov-gigapath, virchow & virchow2 use 224x224 patch_size
# path to directory containing h5 files
data_h5_dirs:
  - /local/data2/chrsp39/CBTN_v2/HE/${target_patch_size}x${target_patch_size}/
  - /local/data2/chrsp39/CBTN_v2/KI67/${target_patch_size}x${target_patch_size}/
  - /local/data2/chrsp39/CBTN_v2/GFAP/${target_patch_size}x${target_patch_size}/
# path to directory containing slide files
data_slide_dirs:
  - /local/data2/chrsp39/CBTN_v2/HE/WSI
  - /local/data2/chrsp39/CBTN_v2/KI67/WSI
  - /local/data2/chrsp39/CBTN_v2/GFAP/WSI
# path to the CSV file listing case_id, slide_id, label
csv_paths:
  - /local/data3/chrsp39/CBTN_v2/CSV_FILES/HE_10_class_dataset.csv
  - /local/data3/chrsp39/CBTN_v2/CSV_FILES/KI67_10_class_dataset.csv
  - /local/data3/chrsp39/CBTN_v2/CSV_FILES/GFAP_10_class_dataset.csv
# output directory to save the features
feat_dirs:
  - /local/data2/chrsp39/CBTN_v2/${model_name}/HE
  - /local/data2/chrsp39/CBTN_v2/${model_name}/KI67
  - /local/data2/chrsp39/CBTN_v2/${model_name}/GFAP


