# CUDA_VISIBLE_DEVICES=0 python extract_features_fp.py
# CUDA_VISIBLE_DEVICES=0 python extract_features_fp_tif.py

# random seed for reproducibility
seed: 1

# -------------------------- DIRECTORY SETTINGS -------------------------- #
# path to directory containing h5 files
data_h5_dir: /run/media/chrsp39/Expansion/CBTN_v2/KI67/${target_patch_size}x${target_patch_size}_svs
# path to directory containing slide files
data_slide_dir: /run/media/chrsp39/Expansion/CBTN_v2/KI67/WSI_svs
# path to the CSV file listing case_id, slide_id, label
csv_path: /local/data3/chrsp39/CBTN_v2/CSVs/KI67_10_class_dataset_svs.csv
# output directory to save the features
feat_dir: /run/media/chrsp39/Expansion/CBTN_v2/KI67/features/${model_name}

# -------------------------- FEATURE EXTRACTION SETTINGS -------------------------- #
# slide file extension
slide_ext: .svs
# feature extractor selection
model_name: conch_v1_5 # options: resnet50, uni, uni2-h, conch_v1, conch_v1_5, hipt, prov-gigapath, virchow, virchow2

# --------------------------- PATCH SETTINGS -------------------------- #
# image patch size 
target_patch_size: 224 

# --------------------------- COMPUTATIONAL SETTINGS -------------------------- #
# batch size for data loading
batch_size: 256
# size of h5 files in GB (only when using virchow and virchow2)
dataset_size_gb: 100 # adjust the size of h5 files to be loaded in memory directly or in chunks if there is memory allocation issues  
# number of worker threads for data loading
num_workers: 12

# --------------------------- PROCESSING SETTINGS -------------------------- #
# skip or not processed slides
auto_skip: True




