description : 'Merged_HE_KI67' 
stain1: 'Merged_HE'
stain2: 'Merged_KI67'

# directory to features
data_root_dir_1: /local/data3/chrsp39/CBTN_v2/${feature_type}/${stain_dual_modality.stain1}/
data_root_dir_2: /local/data3/chrsp39/CBTN_v2/${feature_type}/${stain_dual_modality.stain2}/
# experiment code to load trained models
models_exp_code_1: ${single_stain_modality_task}_${stain_dual_modality.stain1}_${model_size}_${model_type}_${feature_type}_s1
models_exp_code_2: ${single_stain_modality_task}_${stain_dual_modality.stain2}_${model_size}_${model_type}_${feature_type}_s1
# experiment name for saving results
save_exp_code: ${task}_${late_fusion_method}_${stain_dual_modality.description}_${model_size}_${model_type}_${feature_type}

