# CUDA_VISIBLE_DEVICES=0 python evaluate_classifier.py
hydra:
  searchpath:
    - /local/data1/chrsp39/CBTN_Histology_Multi_Stain/configs

defaults:
  - _self_

# -------------------------- GENERAL SETTINGS -------------------------- #
seed: 1

# -------------------------- CLASSIFICATION SETTINGS -------------------------- #
task: 5_class # 5_class, LGG_vs_HGG
n_classes: 5
label_dict:
  LGG: 0
  HGG: 1
  MB: 2
  EP: 3
  GG: 4

# -------------------------- DATA SETTINGS -------------------------- #
csv_path: /local/data3/chrsp39/CBTN_v2/CSVs/Merged_HE_KI67_${task}_dataset.csv
# SUBJECT_LEVEL_CONCATENATION_HE_KI67
# SUBJECT_LEVEL_ELEMENT_WISE_MULT_HE_KI67
# SUBJECT_LEVEL_CROSS_ATTENTION_HE_KI67
test_dir: /local/data3/chrsp39/CBTN_v2/SUBJECT_LEVEL_CROSS_ATTENTION_HE_KI67/50%_split/${task}/features/${feature_type}/test/fold_{fold}
k: 50
k_start: -1
k_end: -1
split_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/splits/Merged_HE_KI67_${task}_0.5_0.2_0.3_100

# -------------------------- FEATURE SETTINGS -------------------------- #
feature_type: conch_v1_5 # options: resnet50, hipt, uni, uni2-h, conch_v1, conch_v1_5
embed_dim: 512 # 512 for CA and EWM, 1024 for CONCAT

# -------------------------- MODEL SETTINGS -------------------------- #
# model directory
# CA, CONCAT, EWM
models_dir: ./results/50%_split/${task}/${task}_Intermediate_Fusion_CA_HE_KI67_${model_size}_${model_type}_${feature_type}_s${seed}
# aggregation menthod
model_type: clam_sb #options: clam_sb, clam_mb, mil, abmil
# size of model, does not affect mil, abmil
model_size: small # option: small, big 
ignore: null

# -------------------------- SAVING SETTINGS -------------------------- #
# CA, CONCAT, EWM
save_dir: ./eval_results/50%_split/${task}/EVAL_${task}_Intermediate_Fusion_CA_HE_KI67_${model_size}_${model_type}_${feature_type}
exp_code: EVAL_${task}_Intermediate_Fusion_CA_HE_KI67_${model_size}_${model_type}_${feature_type}

# -------------------------- EVAL SETTINGS -------------------------- #
micro_average: false
