# CUDA_VISIBLE_DEVICES=0,1 python extract_subject_level_attentions.py -m stain_modality.description=HE,KI67

hydra:
  searchpath:
    - /local/data1/chrsp39/CBTN_Histology_Multi_Stain/configs

# stain_modality description (e.g. HE, KI67)
stain_modality:
  description: HE

# random seed for reproducibility
seed: 1

# -------------------------- CLASSIFICATION SETTINGS -------------------------- #
# classification task
task: 5_class # LGG_vs_HGG, 5_class
# number of class
n_classes: 5

# -------------------------- DATA SETTINGS -------------------------- #
# number of folds
n_folds: 50
splits_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/splits/Merged_HE_KI67_${task}_0.7_0.1_0.2_100
split: test # options: train, val, test

# -------------------------- FEATURE SETTINGS -------------------------- #
# directory to features
features_dir: /local/data3/chrsp39/CBTN_v2/Merged_${stain_modality.description}/features/${feature_type}/pt_files
# type of feature
feature_type: conch_v1 # options: resnet50, hipt, uni, uni2-h, conch_v1, conch_v1_5
# dimensionality of features
embed_dim: 512 

# -------------------------- SAVE SETTINGS -------------------------- #
# directory for saving the subject level attention
save_dir: /local/data3/chrsp39/CBTN_v2/SUBJECT_LEVEL_ATTENTION_${stain_modality.description}/${task}/features/${feature_type}/${split}/pt_files
# experiment code to load trained models
models_exp_code: ${task}_${stain_modality.description}_${model_size}_${model_type}_${feature_type}_s1

# -------------------------- MODEL SETTINGS -------------------------- #
# results directory
results_dir: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/results/${task}
# model type
model_type: clam_sb # options: clam_sb, clam_mb
# model size
model_size: small # option: small, big
# dropout rate
drop_out: 0.0
