# CUDA_VISIBLE_DEVICES=0,1 python intermediate_fusion.py

hydra:
	searchpath:
  - /local/data1/chrsp39/CBTN_Histology_Multi_Stain/configs

defaults:
- _self_

# random seed for reproducibility
seed: 1

# number of folds
n_folds: 50
# start fold 
k_start: -1 # (default: -1, last fold)
# end fold
k_end: -1 # (default: -1, first fold)

# -------------------------- PATH SETTINGS -------------------------- #
# path to HE features
HE_features: /local/data3/chrsp39/CBTN_v2/Merged_HE/features/conch_v1/pt_files
# path to save subject-level attention
save_path_HE: /local/data3/chrsp39/CBTN_v2/Merged_HE_SUBJECT_LEVEL_ATTENTION/features/conch_v1/pt_files
# path to splits
path_to_splits: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/splits/Merged_HE_KI67_LGG_vs_HGG_0.7_0.1_0.2_100
# path to trained model
path_to_trained_model: /local/data1/chrsp39/CBTN_Histology_Multi_Stain/models/CLAM/results/LGG_vs_HGG/LGG_vs_HGG_HE_small_clam_sb_conch_v1_s1

# -------------------------- MODEL SETTINGS -------------------------- #
# model type
model_type: clam_sb # options: clam_sb, clam_mb
# model size
model_size: small # option: small, big
# dropout rate
dropout: 0.0
# number of positive/negative patches to sample for clam
k_sample: 8
# number of classes
n_classes: 2
# dimensionality of features
embed_dim: 512
