description : 'Merged_HE_KI67_GFAP' 

# directory to features
data_root_dir: /local/data2/chrsp39/CBTN_v2/${feature_type}/${stain_modality.description}/
# experiment code to load trained models
models_exp_code: ${task}_${stain_modality.description}_${model_size}_${model_type}_${feature_type}_s1
# experiment name for saving results
save_exp_code: ${task}_${stain_modality.description}_${model_size}_${model_type}_${feature_type}

